name: Build Strawberry BPM .deb

on:
  push:
    branches:
      - releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git cmake build-essential qt6-base-dev qt6-tools-dev qt6-tools-dev-tools libpulse-dev libtag1-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libchromaprint-dev libsqlite3-dev libavcodec-dev libavformat-dev libavutil-dev libswresample-dev libcurl4-openssl-dev libmtp-dev libcdio-dev pkg-config dh-make debhelper fakeroot

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure and build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j$(nproc)

      - name: Create .deb package
        run: |
          cd build
          cpack -G DEB

      - name: Upload .deb as artifact
        uses: actions/upload-artifact@v4
        with:
          name: strawberry-bpm-deb
          path: build/*.deb

